name: Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      
      - name: List directory contents
        run: ls -la
        
        
      - name: Print working directory
        run: pwd
      
      - name: List repository contents
        run: ls -R
        
      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Run bot
        run: python ././chinang_bot.py
