name: Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Make envfile
        uses: src/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "6268503989:AAFIquswj8vkHx0H4sQ2Gm8RkoyaiZimCLY"
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          some_other_variable: foobar
          file_name: .env
          fail_on_empty: false

      # - name: Load .env file
      #   run: |
      #     echo "$(<.env)" >> $GITHUB_ENV
      # - name: Use environment variables
      #   run: |
      #     echo ${{ secrets.MY_VARIABLE }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python chinang_bot.py
