name: Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - name: Run My Workflow Step
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        run: |
          # Use the environment variables in your command or script
          my_command --gpt-api-key $GPT_API_KEY --bot-token $BOT_TOKEN --google-api-key $GOOGLE_API_KEY --google-cse-id $GOOGLE_CSE_ID


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python chinang_bot.py
