name: Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
          
      - name: List files in the repository
        run: |
            ls ${{ github.workspace }}
          

        
      - name: Install dependencies
        run: pip install -r ../../src/requirements.txt

      - name: Run bot
        run: python ./src/chinang_bot.py
