name: Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: Open Web Client Directory
        working-directory: src
        run: |
          ls -la
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - name: Run bot
        run: python BotByTeleGram/src/chinang_bot.py
